# Generated by Django 4.2.6 on 2023-10-30 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("class", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Students",
            new_name="Student",
        ),
    ]
