# Generated by Django 4.2.6 on 2023-10-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("class", "0002_rename_students_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(default="Web development teacher")),
            ],
        ),
    ]
