# Generated by Django 4.2.6 on 2023-11-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("class", "0003_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text1", models.CharField(max_length=100)),
                ("text2", models.CharField(max_length=100)),
                ("image", models.ImageField(default="profile.png", upload_to="images")),
            ],
        ),
    ]
